/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACardMeta: typeof import('ant-design-vue/es')['CardMeta']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    AppContainer: typeof import('./src/components/AppContainer.vue')['default']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATypographyText: typeof import('ant-design-vue/es')['TypographyText']
    ATypographyTitle: typeof import('ant-design-vue/es')['TypographyTitle']
    AuthModal: typeof import('./src/components/AuthModal.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    Container: typeof import('./src/components/Container.vue')['default']
    ImageGallery: typeof import('./src/components/ImageGallery.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PostCard: typeof import('./src/components/PostCard.vue')['default']
    Profile: typeof import('./src/components/Profile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Timeline: typeof import('./src/components/Timeline.vue')['default']
    UserBar: typeof import('./src/components/UserBar.vue')['default']
    UserProfile: typeof import('./src/components/UserProfile.vue')['default']
    UserTimeline: typeof import('./src/components/UserTimeline.vue')['default']
  }
}
